import ply.lex as lex

reserved = {
	'SETQ': "setq",
	'DEFUN': "defun", 
	'QUOTE': "quote", 
	'SET': "set", 
	'T': "t", 
	'NIL': "nil", 
	'CAR': "car", 
	'CDR': "cdr", 
	'NTH': "nth", 
	'NTHCDR': "nthcdr", 
	'LAST': "last", 
	'LENGTH': "length", 
	'FIRST': "first", 
	'REST': "rest", 
	'CONS': "const", 
	'APPEND': "append", 
	'INCR': "incr", 
	'DECR': "decr", 
	'PUSH': "push", 
	'NULL': "null", 
	'LAMBDA':"lambda",
	'DEFMACRO':"defmacro",
	'WRITE-LINE':"write-line",
	'TYPEP':"typep",
	'TYPE-OF':"type-of",
	'DEFVAR':"defvar",
	'WRITE':"write",
	'PROG':"prog",
	'DEFCONSTANT':"defconstant",
	'COND':"cond",
	'IF':"if",
	'WHEN':"when",
	'CASE':"case",
	'LOOP':"loop",
	'LOOP FOR':"loop for",
	'FROM':"from",
	'TO':"to",
	'DO':"do",
	'DOTIMES':"dotimes",

}
